on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: windows-latest  # You can change to macos-latest or ubuntu-latest if needed

    strategy:
      matrix:
        node-version: [16.x]  # Using Node.js 16.x, you can change to a higher version as needed

    steps:
      - uses: actions/checkout@v3  # Updated to v3 to avoid deprecation warnings

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Updated to v3 for future compatibility
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm install

      - name: Install Playwright and browsers
        run: |
          npx playwright install

      - name: Run Playwright tests
        run: npx playwright test session5.spec.ts --project=chromium