on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: windows-latest  # You can change to macos-latest or ubuntu-latest if needed

    strategy:
      matrix:
        node-version: [20.x]  # Switch to Node.js 20.x to align with future defaults

    steps:
      - uses: actions/checkout@v3  # Already using the latest version

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Already using the latest version
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm install

      - name: Install Playwright and browsers
        run: |
          npx playwright install

      - name: Run Playwright tests
        run: |
        export ENV='qa'
        npx playwright test env.spec.ts --project=chrome --headed